### PR TITLE
Fix block link fields in non inline editing

### PR DESCRIPTION
**Pull request by thats4shaw**
Address what seems to be a context issue or load ordering problem around the use of `this` in non inline editable contexts.

### CODE REVIEW

**Comment by Cheddam** [comment]
@thats4shaw Thanks for raising this! I've tested locally and it seems to do the trick - once the JS is recompiled. You'll need to run `yarn build` and commit/push the new dist file up to get the CI passing. When that's done, I'm happy to approve and merge.

**Comment by thats4shaw** [comment]
Ah, only the key ingredient - thanks @Cheddam.  Not sure how I forgot about that, I'll blame the holidays.  

I'm running into some dependency issues during the build.

```
Cannot find module 'components/FieldHolder/FieldHolder' from 'BlockLinkField.js'
```

I wonder if https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/36 needs resolving first.

**Comment by Cheddam** [comment]
Strange - that alias should be provided by `silverstripe/webpack-config` 🤔 I'll take a look.

**Review by Cheddam — APPROVED** [review]
Ran into a different issue locally (something going sideways with Jest) but pushed up a manual production build and the tests are now passing in Travis, so we're good to merge. Thanks again!

**Comment by thats4shaw** [comment]
Thanks for your help getting this across the line @Cheddam!

**Pull request merged**
