### PR TITLE
API phpunit 9 support

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue: https://github.com/silverstripe/silverstripe-framework/issues/10019

### CODE REVIEW

**Comment by emteknetnz** [comment]
Travis failure in php 8.0 is existing

**Comment by maxime-rainville** [comment]
This PR should fix the PHP8 build: https://github.com/silverstripe/silverstripe-event-dispatcher/pull/17

**Comment by maxime-rainville** [comment]
The other PR got merged and I tagged a new release ... however there's some other things that broke in-between I think

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
The the 2 build failures appear to be related to the PHPUnit9 upgrade. 
image

**Review by maxime-rainville — APPROVED** [review]
LGTM

**Pull request merged**
